name: Tests
run-name: Test run
on: [push]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - run: git clone git@github.com:JussiKarkkainen/NetHackRL.git
      - run: cd NetHackRL && python3 -m venv testrunner && source testrunner/bin/activate && pip3 install -r requirements.txt && pytest
      - run: rm -rf ./*
      - run: rm -rf ./.??*

