name: Tests
run-name: Test run
on: [push]
jobs:
  build&test:
    runs-on: self-hosted
    steps:
      - run: git clone git@github.com:JussiKarkkainen/NetHackRL.git && cd NetHackRL
      - run: python3 -m venv testrunner && source testrunner/bin/activate && pip3 install -r requirements.txt && pytest
      - run: rm -fr testrunner
      - run: cd .. && rm -fr NetHackRL

